import express from 'express';
import path from 'path';
import fs from 'fs';
import { fileURLToPath } from 'url';
import dotenv from 'dotenv';
import { GoogleGenAI } from '@google/genai';

dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const app = express();
const port = 3000;

app.use(express.json());

// Initialize server-side Gemini client with aistudio-build telemetry
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY || '',
  httpOptions: {
    headers: {
      'User-Agent': 'aistudio-build',
    }
  }
});

// System instruction matching Section 12 specification
function buildSystemInstruction(tone = 'professional', conciseness = 'balanced') {
  return `You are a professional bilingual language refinement assistant.

The user's input may be:
- Bangla
- English
- Banglish (Bangla written phonetically in English alphabet or mixed)
- mixed Bangla/English codeswitching
- rough speech-to-text with spoken hesitations and transcription noise
- grammatically incorrect
- incomplete
- informal

Your job is to understand the intended meaning and produce two polished versions:

1. Natural professional Bangla:
   - Sounds authentic, respectful, and culturally natural to a Bangladeshi professional.
   - Do NOT produce mechanical word-for-word translation.
   - Use standard formal/semi-formal Bengali (চলিত রীতি).

2. Natural professional English:
   - Sounds fluent, crisp, polite, and executive.
   - Do NOT produce literal Bangla-to-English translation.

Rules:
- Preserve the original meaning and factual details strictly.
- Do NOT invent facts, names, dates, numbers, policies, or technical commitments.
- Correct grammar, spelling, and sentence structure.
- Remove obvious voice-transcription artifacts, filler words, or stutters.
- Tone target: ${tone.toUpperCase()} (Polite, clear, respectful, helpful, confident).
- Length target: ${conciseness.toUpperCase()} (Expressive yet concise; never add filler just to pad length).
- Do NOT mention that this text was generated by AI.
- Do NOT explain your corrections unless explicitly requested.

Return ONLY a valid JSON object matching:
{
  "bangla": "পেশাদার বাংলা রূপান্তর...",
  "english": "Professional English refinement..."
}`;
}

// Backend AI Gateway Route (Option B)
app.post('/api/refine', async (req, res) => {
  try {
    const { transcript, tone = 'professional', conciseness = 'balanced', model } = req.body;

    if (!transcript || typeof transcript !== 'string') {
      return res.status(400).json({ error: 'Valid transcript string is required.' });
    }

    if (!process.env.GEMINI_API_KEY) {
      return res.status(500).json({
        error: 'GEMINI_API_KEY is not configured on the server. Please check the Secrets panel.'
      });
    }

    let chosenModel = model || 'gemini-3.8-flash';
    if (chosenModel === 'gemini-2.5-flash') {
      chosenModel = 'gemini-3.8-flash';
    }

    let response;
    const candidateModels = [chosenModel];
    if (chosenModel !== 'gemini-3.8-flash') candidateModels.push('gemini-3.8-flash');
    if (chosenModel !== 'gemini-3.1-flash-lite') candidateModels.push('gemini-3.1-flash-lite');
    if (chosenModel !== 'gemini-flash-latest') candidateModels.push('gemini-flash-latest');

    let lastError: any = null;

    for (const modelName of candidateModels) {
      for (let attempt = 0; attempt < 2; attempt++) {
        try {
          if (attempt > 0) {
            await new Promise((r) => setTimeout(r, 1000));
          }
          response = await ai.models.generateContent({
            model: modelName,
            contents: transcript,
            config: {
              systemInstruction: buildSystemInstruction(tone, conciseness),
              temperature: 0.3,
              responseMimeType: 'application/json'
            }
          });
          if (response && response.text) {
            break;
          }
        } catch (err: any) {
          lastError = err;
          console.warn(`Attempt ${attempt + 1} for ${modelName} error:`, err?.message || err);
        }
      }
      if (response && response.text) break;
    }

    if (!response || !response.text) {
      throw lastError || new Error('AI refinement model currently busy. Please retry in a few seconds.');
    }

    const rawText = response.text || '';
    const cleaned = rawText.replace(/^```json\s*/i, '').replace(/\s*```$/i, '').trim();
    const parsed = JSON.parse(cleaned);

    res.json({
      bangla: parsed.bangla || '',
      english: parsed.english || ''
    });
  } catch (err: any) {
    console.error('Error in /api/refine:', err);
    res.status(500).json({
      error: err.message || 'Failed to refine voice transcript.'
    });
  }
});

// Download extension ZIP endpoint
app.get('/api/download-extension', (req, res) => {
  const zipPath = path.join(__dirname, 'voice-bilingual-professionalizer-v1.0.0.zip');
  if (fs.existsSync(zipPath)) {
    res.download(zipPath, 'voice-bilingual-professionalizer-v1.0.0.zip');
  } else {
    res.status(404).json({ error: 'Extension package not found. Run packaging script.' });
  }
});

// Read extension file content for the in-app code inspector
app.get('/api/extension-files', (req, res) => {
  try {
    const extDir = path.join(__dirname, 'extension');
    const filesList: Array<{ path: string; size: number }> = [];

    function scan(dir: string, base: string = '') {
      const items = fs.readdirSync(dir, { withFileTypes: true });
      for (const item of items) {
        const rel = base ? `${base}/${item.name}` : item.name;
        if (item.isDirectory()) {
          scan(path.join(dir, item.name), rel);
        } else {
          const stat = fs.statSync(path.join(dir, item.name));
          filesList.push({ path: rel, size: stat.size });
        }
      }
    }

    scan(extDir);
    res.json(filesList);
  } catch (e: any) {
    res.status(500).json({ error: e.message });
  }
});

app.get('/api/extension-file-content', (req, res) => {
  const relPath = req.query.path as string;
  if (!relPath || relPath.includes('..')) {
    return res.status(400).json({ error: 'Invalid path' });
  }

  const fullPath = path.join(__dirname, 'extension', relPath);
  if (fs.existsSync(fullPath)) {
    const content = fs.readFileSync(fullPath, 'utf8');
    res.send(content);
  } else {
    res.status(404).send('File not found');
  }
});

// Health check
app.get('/api/health', (req, res) => {
  res.json({
    status: 'ok',
    version: '1.0.0',
    hasGeminiKey: Boolean(process.env.GEMINI_API_KEY)
  });
});

// Mount Vite or serve static dist
async function setupVite() {
  const isProd = process.env.NODE_ENV === 'production';

  if (!isProd) {
    const { createServer: createViteServer } = await import('vite');
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: 'spa',
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(__dirname, 'dist');
    app.use(express.static(distPath));
    app.get('*', (req, res) => {
      res.sendFile(path.join(distPath, 'index.html'));
    });
  }

  app.listen(port, '0.0.0.0', () => {
    console.log(`Voice Bilingual Professionalizer running at http://0.0.0.0:${port}`);
  });
}

setupVite();
